CREATE TABLE Item(ItemID INTEGER NOT NULL, 
		Name VARCHAR(4000) NOT NULL, 
		Currently DECIMAL(8,2) NOT NULL,
		Buy_Price DECIMAL(8,2) DEFAULT NULL,
		First_Bid DECIMAL(8,2) NOT NULL,
		Number_of_Bids DECIMAL(8,2) NOT NULL,
		Started TIMESTAMP NOT NULL,
		Ends TIMESTAMP NOT NULL,
		Location VARCHAR(4000) DEFAULT NULL,
		Country VARCHAR(4000) DEFAULT NULL,
		SellerID VARCHAR(4000) NOT NULL,
		Description VARCHAR(4000),
		PRIMARY KEY (ItemID) );
CREATE TABLE User(UserID VARCHAR(400) NOT NULL,
		Rating INTEGER NOT NULL );
CREATE TABLE Category(ItemID INTEGER NOT NULL,
		Category VARCHAR(4000) NOT NULL );
CREATE TABLE Bid(ItemID INTEGER NOT NULL,
		UserID VARCHAR(400) NOT NULL,
		Amount DECIMAL(8,2) NOT NULL,
		Time TIMESTAMP NOT NULL );
