LOAD DATA LOCAL INFILE 'uniqueUsers.dat' INTO TABLE User
FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'uniqueBids.dat' INTO TABLE Bid
FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'uniqueCategories.dat' INTO TABLE Category
FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'uniqueItems.dat' INTO TABLE Item
FIELDS TERMINATED BY '|*|';
